sudo: true
dist: trusty

jobs:
  include:
    - stage: test
      script: docker run -it --rm -v $(pwd)/lib/scripts:/bzt-configs -v $(pwd)/lib/artifacts:/tmp/artifacts blazemeter/taurus:latest example.yml
    - stage: test
    - script: docker run -it --rm -v $(pwd)/lib/scripts:/bzt-configs -v $(pwd)/lib/artifacts:/tmp/artifacts blazemeter/taurus:latest PWLoadTestPlan.jmx

addons:
  artifacts:
      paths:
        - ./lib
      target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results/