dist: trusty

jobs:
  include:
    - stage: pull docker taurus
      script:
        - echo "${DOCKER_USERNAME}" | docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        - docker pull blazemeter/taurus
        - docker images
    - stage: test
      script: docker run --rm -v $(pwd)/scripts:/bzt-configs -v $(pwd)/artifacts:/tmp/artifacts blazemeter/taurus

addons:
  artifacts:
      paths:
        - ./artifacts
      target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
