sudo: required
dist: trusty

servises:
  - docker

before_install:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker pull blazemeter/taurus
  - mkdir artifacts
  - ls
  - chmod -R a=rwx $(pwd)
  - docker run --rm -v $(pwd)/scripts:/bzt-configs -v $(pwd)/artifacts:/tmp/artifacts blazemeter/taurus execution.yml

addons:
  artifacts:
      paths:
        - artifacts
      target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results