sudo: true
dist: trusty

jobs:
  include:
    - stage: pull docker taurus
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker pull blazemeter/taurus
      - docker tag blazemeter/taurus blazemeter/taurus:latest
      - docker images
    - stage: test
      script: docker run -it -d --rm -v $(pwd)/lib/scripts:/bzt-configs -v $(pwd)/lib/artifacts:/tmp/artifacts blazemeter/taurus:latest execution.yml
    - script: docker run -it -d --rm -v $(pwd)/lib/scripts:/bzt-configs -v $(pwd)/lib/artifacts:/tmp/artifacts blazemeter/taurus:latest taurus_jmeter_script1.yml 

addons:
  artifacts:
      paths:
        - ./lib
      target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results/